[package]
name = "text_tree_elements"
version = "0.1.0"
authors = ["Anton Gepting <anton.gepting@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
